name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install replace-in-file
        run: npm install -g replace-in-file
        
      - name: Generate and Inject Firebase Config
        run: |
          # Create JSON config manually (no jq needed)
          CONFIG_JSON=$(cat <<EOF
          {
            "apiKey": "${{ secrets.FIREBASE_API_KEY }}",
            "authDomain": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            "databaseURL": "${{ secrets.FIREBASE_DATABASE_URL }}",
            "projectId": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "storageBucket": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "messagingSenderId": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "appId": "${{ secrets.FIREBASE_APP_ID }}"
          }
          EOF
          )
          
          echo "Generated config (redacted): ${CONFIG_JSON:0:50}..."
          
          # Convert to base64
          FIREBASE_CONFIG=$(echo -n "$CONFIG_JSON" | base64 -w 0)
          
          # Replace placeholder
          replace-in-file "@@FIREBASE_CONFIG@@" "$FIREBASE_CONFIG" index.html
          
          # Verify replacement
          if ! grep -q "$FIREBASE_CONFIG" index.html; then
            echo "::error::Config injection failed"
            exit 1
          fi
          
          echo "Config injected successfully"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4