name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install -g replace-in-file jq
        
      - name: Validate Secrets
        run: |
          echo "Checking secrets existence..."
          if [ -z "${{ secrets.FIREBASE_API_KEY }}" ]; then
            echo "::error::FIREBASE_API_KEY is empty"
            exit 1
          fi
          echo "All secrets exist"
          
      - name: Generate and Inject Firebase Config
        run: |
          # Create JSON config
          CONFIG_JSON='{
            "apiKey": "${{ secrets.FIREBASE_API_KEY }}",
            "authDomain": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            "databaseURL": "${{ secrets.FIREBASE_DATABASE_URL }}",
            "projectId": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "storageBucket": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "messagingSenderId": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "appId": "${{ secrets.FIREBASE_APP_ID }}"
          }'
          
          echo "Config JSON created"
          
          # Convert to base64
          FIREBASE_CONFIG=$(echo -n "$CONFIG_JSON" | base64 -w 0)
          echo "Base64 config created (first 20 chars): ${FIREBASE_CONFIG:0:20}..."
          
          # Verify index.html exists
          if [ ! -f "index.html" ]; then
            echo "::error::index.html not found"
            exit 1
          fi
          
          # Replace using sed (more reliable)
          sed -i "s|@@FIREBASE_CONFIG@@|$FIREBASE_CONFIG|g" index.html
          
          # Verify replacement
          if ! grep -q "$FIREBASE_CONFIG" index.html; then
            echo "::error::Config injection verification failed"
            echo "Current placeholder value:"
            grep "@@FIREBASE_CONFIG@@" index.html || echo "Not found"
            exit 1
          fi
          
          echo "Config injected successfully"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4